# Generated by Django 5.2.15 on 2026-06-30 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN_PUSAT', 'Admin Pusat'), ('SATKER', 'Satker'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=20)),
                ('satker_code', models.CharField(blank=True, max_length=32)),
                ('satker_name', models.CharField(blank=True, max_length=255)),
                ('must_change_password', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['role'], name='accounts_pr_role_fae1f3_idx'), models.Index(fields=['satker_code'], name='accounts_pr_satker__6cdca7_idx')],
            },
        ),
    ]
