# Generated by Django 5.2.15 on 2026-07-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satker_code', models.CharField(max_length=32)),
                ('satker_label', models.CharField(max_length=100)),
                ('bulan', models.CharField(max_length=20)),
                ('bulan_number', models.PositiveSmallIntegerField()),
                ('tahun', models.PositiveSmallIntegerField()),
                ('fa16_bulan_ini', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('intermilan_bulan_ini', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('intermilan_sd_bulan_ini', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('persen_realisasi', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('persen_kelengkapan_dokumen', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('persen_spj_upload', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('persen_arsip', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('percent_completed', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('bar', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('excel_seed', 'Excel Seed'), ('calculated', 'Calculated'), ('manual', 'Manual'), ('mixed', 'Mixed')], default='excel_seed', max_length=20)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tahun', 'bulan_number', 'satker_code'],
                'indexes': [models.Index(fields=['tahun', 'bulan_number'], name='core_monito_tahun_ab3aa0_idx'), models.Index(fields=['satker_code', 'tahun'], name='core_monito_satker__2ae012_idx'), models.Index(fields=['source'], name='core_monito_source_d28f04_idx')],
                'constraints': [models.UniqueConstraint(fields=('satker_code', 'bulan_number', 'tahun'), name='unique_monitoring_summary_period_satker')],
            },
        ),
    ]
