# Generated by Django 5.2.16 on 2026-08-11 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('dk', '0004_alter_transactionchangelog_change_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SatkerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(help_text='4-digit unit code from filename (KK_XXXX.xlsx)', max_length=4, unique=True)),
                ('satker_code', models.CharField(help_text='Official 6-digit satker code', max_length=6, unique=True)),
                ('nama_satker', models.CharField(help_text='Full satker name', max_length=255)),
                ('jenis_unit', models.CharField(blank=True, choices=[('PROVINSI', 'Provinsi'), ('KABUPATEN', 'Kabupaten/Kota'), ('KOTA', 'Kota')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Satker Master',
                'verbose_name_plural': 'Satker Masters',
                'ordering': ['satker_code'],
            },
        ),
        migrations.CreateModel(
            name='TransactionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satker_code', models.CharField(db_index=True, help_text='Official 6-digit BPS satker code (e.g., 019937)', max_length=6)),
                ('unit_code', models.CharField(blank=True, db_index=True, help_text='4-digit unit code from filename (e.g., 1300)', max_length=4)),
                ('tahun', models.PositiveSmallIntegerField(db_index=True)),
                ('nomor_spm', models.CharField(db_index=True, max_length=100)),
                ('no_sp2d', models.CharField(blank=True, max_length=100)),
                ('tanggal_sp2d', models.DateField(blank=True, null=True)),
                ('nilai_sp2d', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tanggal_spm', models.DateField(blank=True, null=True)),
                ('jenis_spm', models.CharField(blank=True, max_length=100)),
                ('nilai_spm', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('deskripsi', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SP2D_READY', 'SP2D Siap'), ('SPM_COMPLETE', 'SPM Lengkap'), ('DRPP_AVAILABLE', 'DRPP Tersedia'), ('COMPLETE', 'Lengkap')], default='DRAFT', max_length=20)),
                ('has_sp2d', models.BooleanField(default=False)),
                ('has_spm_document', models.BooleanField(default=False)),
                ('has_drpp', models.BooleanField(default=False)),
                ('sp2d_source', models.CharField(blank=True, max_length=255)),
                ('spm_source', models.CharField(blank=True, max_length=255)),
                ('drpp_count', models.PositiveIntegerField(default=0)),
                ('kuitansi_count', models.PositiveIntegerField(default=0)),
                ('dk_count', models.PositiveIntegerField(default=0)),
                ('active_drpp_parent_key', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transaction Package',
                'verbose_name_plural': 'Transaction Packages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['satker_code', 'tahun', 'nomor_spm'], name='core_transa_satker__45e446_idx'), models.Index(fields=['satker_code', 'no_sp2d'], name='core_transa_satker__a6eaf6_idx'), models.Index(fields=['status', 'satker_code'], name='core_transa_status_8cc0a1_idx'), models.Index(fields=['satker_code', 'tahun'], name='core_transa_satker__ca5136_idx'), models.Index(fields=['tahun'], name='core_transa_tahun_09ded0_idx'), models.Index(fields=['unit_code', 'tahun'], name='core_transa_unit_co_e58a5a_idx')],
                'unique_together': {('satker_code', 'tahun', 'nomor_spm')},
            },
        ),
        migrations.CreateModel(
            name='DRPPPreviewState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('nomor_drpp', models.CharField(max_length=100)),
                ('satker_code', models.CharField(max_length=32)),
                ('tahun', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('frozen_satker_code', models.CharField(blank=True, max_length=32)),
                ('frozen_tahun', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('frozen_nomor_spm', models.CharField(blank=True, max_length=100)),
                ('preview_data', models.JSONField(blank=True, default=dict)),
                ('selection_conflict', models.BooleanField(default=False)),
                ('conflict_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMMITTED', 'Committed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drpp_preview_states', to=settings.AUTH_USER_MODEL)),
                ('frozen_parent_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drpp_previews_as_parent', to='core.transactionpackage')),
            ],
            options={
                'indexes': [models.Index(fields=['session_key', 'user', 'status'], name='core_drpppr_session_25508e_idx'), models.Index(fields=['nomor_drpp', 'satker_code'], name='core_drpppr_nomor_d_4e29a7_idx'), models.Index(fields=['frozen_satker_code', 'frozen_tahun', 'frozen_nomor_spm'], name='core_drpppr_frozen__b4e547_idx'), models.Index(fields=['expires_at'], name='core_drpppr_expires_96d13c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActiveParentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('satker_code', models.CharField(blank=True, max_length=32)),
                ('tahun', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nomor_spm', models.CharField(blank=True, max_length=100)),
                ('tanggal_spm', models.DateField(blank=True, null=True)),
                ('jenis_spm', models.CharField(blank=True, max_length=100)),
                ('selection_method', models.CharField(blank=True, choices=[('EXPLICIT', 'User explicitly selected'), ('AUTO_COMPATIBLE', 'Auto-selected (compatible active)'), ('EVIDENCE_MATCH', 'Matched trusted evidence'), ('FROZEN_PREVIEW', 'Frozen from preview')], max_length=50)),
                ('selection_evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_parent_sessions', to=settings.AUTH_USER_MODEL)),
                ('transaction_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_sessions', to='core.transactionpackage')),
            ],
            options={
                'indexes': [models.Index(fields=['session_key', 'user'], name='core_active_session_205d79_idx'), models.Index(fields=['satker_code', 'tahun', 'nomor_spm'], name='core_active_satker__85ab57_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransactionProvenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SP2D', 'SP2D Import'), ('SPM', 'SPM Document Upload'), ('DRPP', 'DRPP Upload'), ('KK_EXCEL', 'KK Excel Import'), ('MIGRATION', 'Data Migration'), ('MANUAL', 'Manual Entry'), ('LEGACY', 'Legacy Data')], max_length=20)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('source_batch_id', models.CharField(blank=True, max_length=100)),
                ('source_upload_id', models.CharField(blank=True, max_length=100)),
                ('original_satker', models.CharField(blank=True, max_length=32)),
                ('original_tahun', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('original_nomor_spm', models.CharField(blank=True, max_length=100)),
                ('original_nomor_drpp', models.CharField(blank=True, max_length=100)),
                ('original_nomor_kwitansi', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provenances', to='dk.transactiondetail')),
                ('transaction_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provenances', to='core.transactionpackage')),
            ],
            options={
                'verbose_name': 'Transaction Provenance',
                'verbose_name_plural': 'Transaction Provenances',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_type'], name='core_transa_source__fadfd9_idx'), models.Index(fields=['source_filename'], name='core_transa_source__8a62e5_idx'), models.Index(fields=['transaction_package', 'source_type'], name='core_transa_transac_afb804_idx')],
            },
        ),
    ]
