# Generated by Django 5.2.15 on 2026-06-30 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dokumen', models.CharField(max_length=255)),
                ('kategori', models.CharField(blank=True, max_length=100)),
                ('wajib', models.BooleanField(default=True)),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['urutan', 'nama_dokumen'],
                'indexes': [models.Index(fields=['kategori'], name='documents_c_kategor_0fbe39_idx'), models.Index(fields=['is_active'], name='documents_c_is_acti_a19039_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/documents/%Y/%m/')),
                ('file_hash', models.CharField(blank=True, max_length=128)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('transaction_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_uploads', to='dk.transactiondetail')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dokumen', models.CharField(max_length=255)),
                ('wajib', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ADA', 'Ada'), ('BELUM', 'Belum'), ('TIDAK_PERLU', 'Tidak Perlu')], default='BELUM', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_statuses', to='dk.transactiondetail')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_checklists', to=settings.AUTH_USER_MODEL)),
                ('dokumen_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_statuses', to='documents.documentupload')),
            ],
            options={
                'ordering': ['nama_dokumen'],
            },
        ),
        migrations.AddIndex(
            model_name='documentupload',
            index=models.Index(fields=['document_type'], name='documents_d_documen_86b83b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentupload',
            index=models.Index(fields=['file_hash'], name='documents_d_file_ha_73aee7_idx'),
        ),
        migrations.AddIndex(
            model_name='checkliststatus',
            index=models.Index(fields=['status'], name='documents_c_status_b0f6ca_idx'),
        ),
        migrations.AddIndex(
            model_name='checkliststatus',
            index=models.Index(fields=['wajib'], name='documents_c_wajib_432dd6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='checkliststatus',
            unique_together={('transaction_detail', 'nama_dokumen')},
        ),
    ]
