# Generated by Django 5.2.15 on 2026-06-30 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk', '0002_masterakun'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDriveLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satker_code', models.CharField(blank=True, max_length=32)),
                ('nomor_spm', models.CharField(blank=True, max_length=100)),
                ('no_kuitansi', models.CharField(blank=True, max_length=100)),
                ('no_drpp', models.CharField(blank=True, max_length=100)),
                ('jenis_dokumen', models.CharField(blank=True, max_length=100)),
                ('nama_file', models.CharField(blank=True, max_length=255)),
                ('google_drive_url', models.URLField(max_length=1000)),
                ('status', models.CharField(choices=[('AKTIF', 'Aktif'), ('PERLU_DICEK', 'Perlu Dicek'), ('TIDAK_AKTIF', 'Tidak Aktif')], default='AKTIF', max_length=20)),
                ('catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drive_links', to=settings.AUTH_USER_MODEL)),
                ('transaction_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive_links', to='dk.transactiondetail')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['satker_code', 'nomor_spm'], name='documents_d_satker__2b548d_idx'), models.Index(fields=['no_kuitansi'], name='documents_d_no_kuit_96c147_idx'), models.Index(fields=['no_drpp'], name='documents_d_no_drpp_75d33a_idx'), models.Index(fields=['jenis_dokumen'], name='documents_d_jenis_d_78529c_idx'), models.Index(fields=['status'], name='documents_d_status_e0bd41_idx')],
            },
        ),
    ]
