# apps/documents/services/google_oauth.py
"""
Google Drive OAuth 2.0 Central Archive Service.

Mendukung upload ke Google Drive dengan SATU akun pusat INTERMILAN.
HANYA admin/superuser boleh authorize. Operator cukup upload.

ROOT FOLDER STRATEGY:
1. Jika GOOGLE_DRIVE_ROOT_FOLDER_ID diset → gunakan langsung
2. Jika kosong → app buat folder otomatis via Drive API
3. Folder ID disimpan di media/drive_tokens/archive_folder_id.json
4. Folder creation idempotent (cari dulu, baru buat jika tidak ada)

CREDENTIAL SECURITY:
- OAuth client_id/client_secret: dari environment variable
- Central token: disimpan di media/drive_tokens/archive_oauth.json (gitignored)
- Folder ID: disimpan di media/drive_tokens/archive_folder_id.json (gitignored)
- Tidak ada credential di source code atau log

CARA PERGANTIAN AKUN:
1. Hapus file token: media/drive_tokens/archive_oauth.json
2. Hapus folder ID: media/drive_tokens/archive_folder_id.json
3. Admin authorize ulang dengan akun baru
4. Folder root akan dibuat ulang secara otomatis
"""

import os
import json
from pathlib import Path
from typing import Optional

from django.conf import settings


# OAuth 2.0 Scopes - least privilege
SCOPES = [
    "https://www.googleapis.com/auth/drive.file",
]


class GoogleOAuthError(Exception):
    """Base exception for Google OAuth errors."""
    pass


class OAuthCredentialsNotConfigured(GoogleOAuthError):
    """OAuth credentials not configured in environment."""
    pass


class OAuthTokenNotFound(GoogleOAuthError):
    """Central OAuth token not found."""
    pass


class OAuthRefreshFailed(GoogleOAuthError):
    """Failed to refresh OAuth token."""
    pass


# =============================================================================
# CONFIGURATION
# =============================================================================

def get_oauth_config() -> dict:
    """
    Ambil konfigurasi OAuth dari environment variables.

    Environment variables yang diperlukan:
    - GOOGLE_DRIVE_OAUTH_CLIENT_ID: OAuth 2.0 Client ID dari Google Cloud Console
    - GOOGLE_DRIVE_OAUTH_CLIENT_SECRET: OAuth 2.0 Client Secret
    - GOOGLE_DRIVE_OAUTH_REDIRECT_URI: Redirect URI

    Returns:
        dict dengan client_id, client_secret, redirect_uri

    Raises:
        OAuthCredentialsNotConfigured: Jika credential tidak ditemukan
    """
    client_id = os.environ.get("GOOGLE_DRIVE_OAUTH_CLIENT_ID", "").strip()
    client_secret = os.environ.get("GOOGLE_DRIVE_OAUTH_CLIENT_SECRET", "").strip()
    redirect_uri = os.environ.get("GOOGLE_DRIVE_OAUTH_REDIRECT_URI", "").strip()

    if not client_id or not client_secret:
        raise OAuthCredentialsNotConfigured(
            "OAuth credentials not configured. "
            "Set GOOGLE_DRIVE_OAUTH_CLIENT_ID and GOOGLE_DRIVE_OAUTH_CLIENT_SECRET."
        )

    return {
        "client_id": client_id,
        "client_secret": client_secret,
        "redirect_uri": redirect_uri or "http://localhost:8000/documents/drive/oauth/callback/",
    }


def get_central_token_path() -> Path:
    """
    Path penyimpanan token OAuth central aplikasi.

    Returns:
        Path ke file token (media/drive_tokens/archive_oauth.json)
    """
    token_dir = Path(settings.MEDIA_ROOT) / "drive_tokens"
    token_dir.mkdir(parents=True, exist_ok=True)
    return token_dir / "archive_oauth.json"


def get_root_folder_id_path() -> Path:
    """
    Path penyimpanan folder ID central aplikasi.

    Returns:
        Path ke file folder ID (media/drive_tokens/archive_folder_id.json)
    """
    token_dir = Path(settings.MEDIA_ROOT) / "drive_tokens"
    token_dir.mkdir(parents=True, exist_ok=True)
    return token_dir / "archive_folder_id.json"


def get_root_folder_name() -> str:
    """
    Nama folder root untuk archive.

    Can be overridden via environment variable GOOGLE_DRIVE_ROOT_FOLDER_NAME.

    Returns:
        Nama folder root
    """
    return os.environ.get(
        "GOOGLE_DRIVE_ROOT_FOLDER_NAME",
        "INTERMILAN - TEST ARSIP"  # Default for testing
    ).strip()


# =============================================================================
# TOKEN MANAGEMENT
# =============================================================================

def get_authorization_url() -> str:
    """
    Generate Google OAuth authorization URL untuk central archive.

    Returns:
        Google authorization URL
    """
    _, auth_url, _ = get_authorization_url_with_flow()
    return auth_url


def get_authorization_url_with_flow():
    """
    Generate Google OAuth authorization URL and return URL, state, Flow, and client_config.

    The Flow object holds the PKCE code_verifier (auto-generated by the library
    when authorization_url() is called). The caller MUST store the Flow's
    code_verifier in the session so the callback can restore it.

    IMPORTANT: Store client_config (with "web" top-level key) in the session,
    NOT flow.client_config — the latter is the unwrapped inner dict and would
    cause "Client secrets must be for a web or installed app." in the callback.

    Returns:
        Tuple of (state, auth_url, flow, client_config)
        - state: CSRF nonce to validate in callback
        - auth_url: Google authorization URL to redirect to
        - flow: Flow object — MUST persist flow.code_verifier for callback use
        - client_config: Full config dict with "web" top-level key (store in session)
    """
    import base64
    import secrets

    from google_auth_oauthlib.flow import Flow

    config = get_oauth_config()

    client_config = {
        "web": {
            "client_id": config["client_id"],
            "client_secret": config["client_secret"],
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "redirect_uris": [config["redirect_uri"]],
        }
    }

    # Create flow with minimal scopes and PKCE enabled (autogenerate_code_verifier=True by default)
    flow = Flow.from_client_config(
        client_config=client_config,
        scopes=SCOPES,
        redirect_uri=config["redirect_uri"],
    )

    # Generate state with nonce for CSRF protection
    state = base64.b64encode(
        json.dumps({"nonce": secrets.token_hex(16)}).encode()
    ).decode()

    # authorization_url() auto-generates code_verifier on the Flow object (PKCE).
    # We MUST return the flow so the caller can store the code_verifier in the session.
    auth_url, _ = flow.authorization_url(
        access_type="offline",
        prompt="consent",  # Force consent to get refresh token
        state=state,
    )

    return state, auth_url, flow, client_config


def exchange_code_for_tokens(code: str, state: str) -> dict:
    """
    Exchange authorization code for tokens.

    Args:
        code: Authorization code from Google
        state: State parameter from callback

    Returns:
        Token dict dengan access_token, refresh_token, expiry
    """
    import base64

    from google_auth_oauthlib.flow import Flow

    config = get_oauth_config()

    # Verify state
    if state:
        try:
            state_data = json.loads(base64.b64decode(state).decode())
            if "nonce" not in state_data:
                raise GoogleOAuthError("Invalid state: missing nonce")
        except Exception as e:
            raise GoogleOAuthError(f"Invalid state: {e}")

    flow = Flow.from_client_config(
        client_config={
            "web": {
                "client_id": config["client_id"],
                "client_secret": config["client_secret"],
                "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                "token_uri": "https://oauth2.googleapis.com/token",
                "redirect_uris": [config["redirect_uri"]],
            }
        },
        scopes=SCOPES,
    )
    flow.redirect_uri = config["redirect_uri"]

    try:
        flow.fetch_token(code=code)
    except Exception as e:
        raise GoogleOAuthError(f"Failed to fetch token: {e}")

    credentials = flow.credentials

    # Save tokens to CENTRAL location
    token_data = {
        "token": credentials.token,
        "refresh_token": credentials.refresh_token,
        "token_uri": credentials.token_uri,
        "client_id": credentials.client_id,
        "client_secret": credentials.client_secret,
        "scopes": credentials.scopes,
        "expiry": credentials.expiry.isoformat() if credentials.expiry else None,
    }

    token_path = get_central_token_path()
    with open(token_path, "w") as f:
        json.dump(token_data, f, indent=2)

    return token_data


def get_central_credentials():
    """
    Ambil credentials central dari stored token.

    Returns:
        google.oauth2.credentials.Credentials object

    Raises:
        OAuthTokenNotFound: Jika token tidak ditemukan
        OAuthRefreshFailed: Jika refresh gagal
    """
    from google.oauth2.credentials import Credentials
    from google.auth.transport.requests import Request

    token_path = get_central_token_path()

    if not token_path.exists():
        raise OAuthTokenNotFound("Central OAuth token not found. Admin perlu authorize terlebih dahulu.")

    with open(token_path, "r") as f:
        token_data = json.load(f)

    credentials = Credentials(
        token=token_data.get("token"),
        refresh_token=token_data.get("refresh_token"),
        token_uri=token_data.get("token_uri", "https://oauth2.googleapis.com/token"),
        client_id=token_data.get("client_id"),
        client_secret=token_data.get("client_secret"),
        scopes=token_data.get("scopes"),
    )

    # Check if expired and refresh if needed
    if credentials.expired and credentials.refresh_token:
        try:
            credentials.refresh(Request())
            # Save refreshed token
            token_data["token"] = credentials.token
            token_data["expiry"] = credentials.expiry.isoformat() if credentials.expiry else None
            with open(token_path, "w") as f:
                json.dump(token_data, f, indent=2)
        except Exception as e:
            raise OAuthRefreshFailed(f"Token refresh failed: {e}")

    return credentials


def has_central_token() -> bool:
    """
    Cek apakah central token sudah ada.

    Returns:
        True jika token ada
    """
    token_path = get_central_token_path()
    return token_path.exists()


def delete_central_token() -> bool:
    """
    Hapus central token (untuk reset/re-authorize).

    Returns:
        True jika token dihapus, False jika tidak ada
    """
    token_path = get_central_token_path()
    if token_path.exists():
        token_path.unlink()
        return True
    return False


def delete_central_folder_id() -> bool:
    """
    Hapus central folder ID (untuk recreate).

    Returns:
        True jika folder ID dihapus, False jika tidak ada
    """
    folder_path = get_root_folder_id_path()
    if folder_path.exists():
        folder_path.unlink()
        return True
    return False


def delete_all_central_credentials():
    """
    Hapus semua central credentials (token + folder ID).

    Untuk full reset saat ganti akun.
    """
    token_deleted = delete_central_token()
    folder_deleted = delete_central_folder_id()
    return token_deleted or folder_deleted


def is_oauth_configured() -> bool:
    """
    Cek apakah OAuth sudah dikonfigurasi.

    Returns:
        True jika client_id dan client_secret tersedia
    """
    try:
        get_oauth_config()
        return True
    except OAuthCredentialsNotConfigured:
        return False
