# Generated by Django 5.2.15 on 2026-06-30 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaketSPMUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(upload_to='uploads/paket_spm/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('folder_path', models.CharField(blank=True, max_length=500)),
                ('nomor_spm', models.CharField(blank=True, max_length=100)),
                ('satker_code', models.CharField(blank=True, max_length=32)),
                ('tahun', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bulan', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('jenis_spm_asli', models.CharField(blank=True, max_length=100)),
                ('jenis_spm_label', models.CharField(blank=True, max_length=100)),
                ('tanggal_spm', models.DateField(blank=True, null=True)),
                ('nilai_spm', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_rincian_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_rincian_netto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('selisih', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PREVIEW', 'Preview'), ('COMMITTED', 'Committed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_paket_spm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PaketSPMPreviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helper', models.CharField(blank=True, max_length=255)),
                ('akun', models.CharField(blank=True, max_length=32)),
                ('bulan_sp2d', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cara_pembayaran', models.CharField(blank=True, max_length=100)),
                ('nomor_spm', models.CharField(blank=True, max_length=100)),
                ('tanggal_spm', models.DateField(blank=True, null=True)),
                ('jenis_spm', models.CharField(blank=True, max_length=100)),
                ('no_kuitansi', models.CharField(blank=True, max_length=100)),
                ('no_drpp', models.CharField(blank=True, max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('nilai_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('nilai_netto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('pembebanan', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('MATCHED', 'Matched'), ('PERLU_DICEK', 'Perlu Dicek'), ('SKIP', 'Skip')], default='DRAFT', max_length=20)),
                ('catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paket_spm_preview_items', to='dk.transactiondetail')),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_items', to='paket_spm.paketspmupload')),
            ],
            options={
                'ordering': ['paket', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='paketspmupload',
            index=models.Index(fields=['satker_code', 'nomor_spm'], name='paket_spm_p_satker__a6e703_idx'),
        ),
        migrations.AddIndex(
            model_name='paketspmupload',
            index=models.Index(fields=['tahun', 'bulan'], name='paket_spm_p_tahun_1140f0_idx'),
        ),
        migrations.AddIndex(
            model_name='paketspmupload',
            index=models.Index(fields=['status'], name='paket_spm_p_status_54271f_idx'),
        ),
        migrations.AddIndex(
            model_name='paketspmpreviewitem',
            index=models.Index(fields=['nomor_spm', 'no_kuitansi'], name='paket_spm_p_nomor_s_4b0e4d_idx'),
        ),
        migrations.AddIndex(
            model_name='paketspmpreviewitem',
            index=models.Index(fields=['nomor_spm', 'no_drpp'], name='paket_spm_p_nomor_s_b1530a_idx'),
        ),
        migrations.AddIndex(
            model_name='paketspmpreviewitem',
            index=models.Index(fields=['akun'], name='paket_spm_p_akun_d13d15_idx'),
        ),
        migrations.AddIndex(
            model_name='paketspmpreviewitem',
            index=models.Index(fields=['status'], name='paket_spm_p_status_4b380a_idx'),
        ),
    ]
