# Generated by Django 5.2.15 on 2026-07-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paket_spm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paketspmpreviewitem',
            name='fp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paketspmpreviewitem',
            name='pph21',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='paketspmupload',
            name='nomor_invoice',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paketspmupload',
            name='nomor_sp2d',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paketspmupload',
            name='parsed_data',
            field=models.JSONField(blank=True, help_text='Menyimpan hasil raw extract/OCR agar tidak diproses berulang kali saat preview.', null=True),
        ),
    ]
