# Generated by Django 5.2.15 on 2026-06-30 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dk', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DRPPItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_urut', models.PositiveIntegerField(blank=True, null=True)),
                ('no_bukti', models.CharField(blank=True, max_length=100)),
                ('no_bukti_norm', models.CharField(blank=True, max_length=100)),
                ('tanggal_bukti', models.DateField(blank=True, null=True)),
                ('penerima', models.CharField(blank=True, max_length=255)),
                ('keperluan', models.TextField(blank=True)),
                ('npwp', models.CharField(blank=True, max_length=50)),
                ('akun', models.CharField(blank=True, max_length=32)),
                ('jumlah', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status_verifikasi', models.CharField(choices=[('BELUM_DICEK', 'Belum Dicek'), ('SESUAI', 'Sesuai'), ('TIDAK_SESUAI', 'Tidak Sesuai'), ('PERLU_REVIEW', 'Perlu Review')], default='BELUM_DICEK', max_length=20)),
                ('catatan', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['drpp_upload', 'no_urut', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DRPPUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_drpp', models.CharField(blank=True, max_length=100)),
                ('nomor_drpp_norm', models.CharField(blank=True, max_length=100)),
                ('tanggal_drpp', models.DateField(blank=True, null=True)),
                ('jenis_spp', models.CharField(blank=True, max_length=100)),
                ('bulan', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tahun', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('satker_code', models.CharField(blank=True, max_length=32)),
                ('nomor_spm', models.CharField(blank=True, max_length=100)),
                ('total_jumlah', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('raw_text', models.TextField(blank=True)),
                ('match_status', models.CharField(choices=[('BELUM_DIPROSES', 'Belum Diproses'), ('COCOK', 'Cocok'), ('PERLU_DICEK', 'Perlu Dicek'), ('KONFLIK', 'Konflik')], default='BELUM_DIPROSES', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('document_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drpp_uploads', to='documents.documentupload')),
                ('transaction_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drpp_uploads', to='dk.transactiondetail')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_drpps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DRPPMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_match', models.CharField(choices=[('COCOK_OTOMATIS', 'Cocok Otomatis'), ('COCOK_MANUAL', 'Cocok Manual'), ('PERLU_DICEK', 'Perlu Dicek'), ('KONFLIK', 'Konflik'), ('TIDAK_ADA_DI_DK', 'Tidak Ada di D_K')], default='PERLU_DICEK', max_length=20)),
                ('skor_match', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_manual', models.BooleanField(default=False)),
                ('catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drpp_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='drpp.drppitem')),
                ('transaction_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drpp_matches', to='dk.transactiondetail')),
                ('drpp_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='drpp.drppupload')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='drppitem',
            name='drpp_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='drpp.drppupload'),
        ),
        migrations.AddIndex(
            model_name='drppupload',
            index=models.Index(fields=['satker_code', 'nomor_spm'], name='drpp_drppup_satker__4fa042_idx'),
        ),
        migrations.AddIndex(
            model_name='drppupload',
            index=models.Index(fields=['nomor_drpp_norm'], name='drpp_drppup_nomor_d_5135f8_idx'),
        ),
        migrations.AddIndex(
            model_name='drppupload',
            index=models.Index(fields=['tahun', 'bulan'], name='drpp_drppup_tahun_1ad815_idx'),
        ),
        migrations.AddIndex(
            model_name='drppupload',
            index=models.Index(fields=['match_status'], name='drpp_drppup_match_s_1d2dc7_idx'),
        ),
        migrations.AddIndex(
            model_name='drppmatch',
            index=models.Index(fields=['status_match'], name='drpp_drppma_status__1f12fd_idx'),
        ),
        migrations.AddIndex(
            model_name='drppmatch',
            index=models.Index(fields=['is_manual'], name='drpp_drppma_is_manu_d0c6fc_idx'),
        ),
        migrations.AddIndex(
            model_name='drppitem',
            index=models.Index(fields=['no_bukti_norm'], name='drpp_drppit_no_bukt_0285a1_idx'),
        ),
        migrations.AddIndex(
            model_name='drppitem',
            index=models.Index(fields=['akun'], name='drpp_drppit_akun_c8386f_idx'),
        ),
        migrations.AddIndex(
            model_name='drppitem',
            index=models.Index(fields=['status_verifikasi'], name='drpp_drppit_status__87f78f_idx'),
        ),
    ]
