# Generated by Django 5.2.15 on 2026-07-24 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drpp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drppitem',
            name='identity_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='drppitem',
            name='nilai_bruto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='drppitem',
            name='nilai_netto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='drppitem',
            name='potongan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='drppitem',
            name='satker_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='drppitem',
            name='source_row_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='drppitem',
            name='source_type',
            field=models.CharField(choices=[('DRPP_ITEM', 'Item DRPP'), ('KUITANSI_MANDIRI', 'Kuitansi Mandiri')], default='DRPP_ITEM', max_length=30),
        ),
        migrations.AddField(
            model_name='drppitem',
            name='tahun',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drppupload',
            name='identity_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='drppitem',
            name='drpp_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='drpp.drppupload'),
        ),
        migrations.AlterField(
            model_name='drppmatch',
            name='drpp_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match', to='drpp.drppitem'),
        ),
        migrations.AlterField(
            model_name='drppmatch',
            name='drpp_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='drpp.drppupload'),
        ),
        migrations.CreateModel(
            name='DRPPImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('created_rows', models.PositiveIntegerField(default=0)),
                ('updated_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('conflict_rows', models.PositiveIntegerField(default=0)),
                ('review_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PROCESSED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drpp_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='drppitem',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='drpp.drppimportbatch'),
        ),
        migrations.AddField(
            model_name='drppupload',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drpp_uploads', to='drpp.drppimportbatch'),
        ),
        migrations.AddIndex(
            model_name='drppitem',
            index=models.Index(fields=['satker_code', 'tahun'], name='drpp_drppit_satker__407b93_idx'),
        ),
        migrations.AddConstraint(
            model_name='drppitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('drpp_upload__isnull', False), ('source_type', 'DRPP_ITEM')), models.Q(('drpp_upload__isnull', True), ('source_type', 'KUITANSI_MANDIRI')), _connector='OR'), name='drpp_item_source_type_constraint', violation_error_message='DRPP_ITEM must have drpp_upload, KUITANSI_MANDIRI must have drpp_upload as NULL'),
        ),
    ]
