# Generated by Django 5.2.15 on 2026-07-27 01:26

import hashlib
import django.db.models.deletion
from django.db import migrations, models


def backfill_phase_31_audit_fields(apps, schema_editor):
    Batch = apps.get_model("drpp", "DRPPImportBatch")
    Item = apps.get_model("drpp", "DRPPItem")
    Upload = apps.get_model("drpp", "DRPPUpload")

    for batch in Batch.objects.all().iterator():
        batch.total_rows = sum(
            getattr(batch, field)
            for field in (
                "created_rows",
                "updated_rows",
                "skipped_rows",
                "conflict_rows",
                "review_rows",
                "failed_rows",
            )
        )
        if batch.status == "PROCESSED":
            batch.status = "COMPLETED"
        batch.save(update_fields=["total_rows", "status"])

    seen_source_keys = set()
    for item in Item.objects.exclude(source_row_key="").order_by("pk").iterator():
        if item.source_row_key in seen_source_keys:
            item.source_row_key = hashlib.sha256(
                f"legacy:{item.source_row_key}:{item.pk}".encode("utf-8")
            ).hexdigest()
        seen_source_keys.add(item.source_row_key)
        item.source_row_id = f"legacy:{item.pk}"
        item.save(update_fields=["source_row_key", "source_row_id"])

    for upload in Upload.objects.exclude(import_batch=None).iterator():
        upload.first_import_batch_id = upload.import_batch_id
        upload.last_import_batch_id = upload.import_batch_id
        upload.save(update_fields=["first_import_batch", "last_import_batch"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentdrivelink'),
        ('drpp', '0002_drppitem_identity_key_drppitem_nilai_bruto_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='drppitem',
            name='drpp_item_source_type_constraint',
        ),
        migrations.AddField(
            model_name='drppimportbatch',
            name='document_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drpp_batches', to='documents.documentupload'),
        ),
        migrations.AddField(
            model_name='drppimportbatch',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='drppimportbatch',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='drppimportbatch',
            name='satker_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='drppimportbatch',
            name='tahun',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drppimportbatch',
            name='total_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drppitem',
            name='source_file_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='drppitem',
            name='source_member_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='drppitem',
            name='source_row_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='drppupload',
            name='first_import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_seen_drpp_uploads', to='drpp.drppimportbatch'),
        ),
        migrations.AddField(
            model_name='drppupload',
            name='last_import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_drpp_uploads', to='drpp.drppimportbatch'),
        ),
        migrations.AlterField(
            model_name='drppimportbatch',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('COMPLETED_WITH_REVIEW', 'Completed with review'), ('FAILED', 'Failed')], default='PROCESSING', max_length=32),
        ),
        migrations.AlterField(
            model_name='drppitem',
            name='source_row_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='drppitem',
            name='source_type',
            field=models.CharField(choices=[('DRPP_ITEM', 'Item DRPP'), ('KUITANSI_MANDIRI', 'Kuitansi Mandiri'), ('UNRESOLVED', 'Sumber Belum Teridentifikasi')], default='DRPP_ITEM', max_length=30),
        ),
        migrations.RunPython(backfill_phase_31_audit_fields, noop_reverse),
        migrations.AddConstraint(
            model_name='drppitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('drpp_upload__isnull', False), ('source_type', 'DRPP_ITEM')), models.Q(('drpp_upload__isnull', True), ('source_type__in', ['KUITANSI_MANDIRI', 'UNRESOLVED'])), _connector='OR'), name='drpp_item_source_type_constraint', violation_error_message='DRPP_ITEM requires a parent; standalone/unresolved sources must not have one'),
        ),
        migrations.AddConstraint(
            model_name='drppitem',
            constraint=models.UniqueConstraint(condition=models.Q(('source_row_key', ''), _negated=True), fields=('source_row_key',), name='unique_drpp_source_row_key'),
        ),
    ]
