# Generated by Django 5.2.16 on 2026-08-14 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentdrivelink'),
        ('drpp', '0003_remove_drppitem_drpp_item_source_type_constraint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DRPPSupportingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satker_code', models.CharField(blank=True, max_length=32)),
                ('tahun', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nomor_drpp', models.CharField(blank=True, max_length=100)),
                ('nomor_drpp_norm', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archive_link', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drpp_supporting_attachment', to='documents.documentdrivelink')),
                ('document_upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drpp_supporting_attachment', to='documents.documentupload')),
                ('drpp_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_attachments', to='drpp.drppupload')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_drpp_supporting_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['satker_code', 'tahun', 'nomor_drpp_norm'], name='drpp_drppsu_satker__95a8cd_idx'), models.Index(fields=['created_at'], name='drpp_drppsu_created_188f0d_idx')],
            },
        ),
    ]
