# Generated by Django 5.2.16 on 2026-08-14 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drpp', '0004_drppsupportingattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drppsupportingattachment',
            name='drpp_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_attachments', to='drpp.drppupload'),
        ),
    ]
