# Generated by Django 5.2.15 on 2026-06-30 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sp2d', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satker_code', models.CharField(blank=True, max_length=32)),
                ('akun', models.CharField(max_length=32)),
                ('kategori', models.CharField(blank=True, max_length=100)),
                ('bulan_sp2d', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cara_pembayaran', models.CharField(blank=True, max_length=100)),
                ('nomor_spm', models.CharField(blank=True, max_length=100)),
                ('tanggal_spm', models.DateField(blank=True, null=True)),
                ('jenis_spm', models.CharField(blank=True, max_length=100)),
                ('no_kuitansi', models.CharField(blank=True, max_length=100)),
                ('no_drpp', models.CharField(blank=True, max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('nilai_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('nilai_netto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('pembebanan', models.CharField(blank=True, max_length=255)),
                ('fp', models.CharField(blank=True, max_length=100)),
                ('pph21', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status_detail', models.CharField(choices=[('DRAFT', 'Draft'), ('LENGKAP', 'Lengkap'), ('PERLU_REVIEW', 'Perlu Review')], default='DRAFT', max_length=20)),
                ('drpp_status', models.CharField(choices=[('BELUM_ADA', 'Belum Ada'), ('ADA', 'Ada'), ('PERLU_DICEK', 'Perlu Dicek'), ('COCOK', 'Cocok')], default='BELUM_ADA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transaction_details', to=settings.AUTH_USER_MODEL)),
                ('sp2d_raw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_details', to='sp2d.sp2draw')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['satker_code', 'nomor_spm'], name='dk_transact_satker__5647fe_idx'), models.Index(fields=['nomor_spm', 'no_kuitansi'], name='dk_transact_nomor_s_afabd1_idx'), models.Index(fields=['nomor_spm', 'no_drpp'], name='dk_transact_nomor_s_deebe4_idx'), models.Index(fields=['akun'], name='dk_transact_akun_8b95d9_idx'), models.Index(fields=['bulan_sp2d'], name='dk_transact_bulan_s_da0b3b_idx')],
            },
        ),
    ]
