# Generated by Django 5.2.15 on 2026-06-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterAkun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=32, unique=True)),
                ('nama_akun', models.CharField(max_length=255)),
                ('kategori', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kode'],
                'indexes': [models.Index(fields=['kategori'], name='dk_masterak_kategor_42b6e5_idx'), models.Index(fields=['is_active'], name='dk_masterak_is_acti_55be56_idx')],
            },
        ),
    ]
