# Generated by Django 5.2.15 on 2026-07-24 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk', '0002_masterakun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='status_detail',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('LENGKAP', 'Lengkap'), ('PERLU_REVIEW', 'Perlu Review'), ('MENUNGGU_SPM', 'Menunggu SPM'), ('MENUNGGU_SP2D', 'Menunggu SP2D'), ('BELUM_SEIMBANG', 'Belum Seimbang'), ('SIAP_FINAL', 'Siap Final'), ('FINAL', 'Final'), ('DIARSIPKAN', 'Diarsipkan')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='TransactionChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('change_source', models.CharField(max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='dk.transactiondetail')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
