# Generated by Django 5.2.15 on 2026-07-24 02:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk', '0003_alter_transactiondetail_status_detail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionchangelog',
            name='change_source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('PARSER', 'Parser'), ('IMPORT', 'Import'), ('SYSTEM', 'System')], default='MANUAL', max_length=50),
        ),
        migrations.AddIndex(
            model_name='transactionchangelog',
            index=models.Index(fields=['transaction', 'changed_at'], name='dk_transact_transac_9b2b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionchangelog',
            index=models.Index(fields=['transaction', 'field_name', 'change_source'], name='dk_transact_transac_ed282a_idx'),
        ),
    ]
