# Generated by Django 5.2.16 on 2026-08-11 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_satker_master_and_package_models'),
        ('dk', '0004_alter_transactionchangelog_change_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetail',
            name='transaction_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_details', to='core.transactionpackage'),
        ),
    ]
