# Generated by Django 5.2.15 on 2026-06-30 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SP2DImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('tahun', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bulan', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('success_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sp2d_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SP2DRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satker_code', models.CharField(blank=True, max_length=32)),
                ('satker_name', models.CharField(blank=True, max_length=255)),
                ('no_sp2d', models.CharField(blank=True, max_length=100)),
                ('tanggal_selesai_sp2d', models.DateField(blank=True, null=True)),
                ('tgl_sp2d', models.DateField(blank=True, null=True)),
                ('mata_uang', models.CharField(blank=True, max_length=20)),
                ('nilai_spm', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('potongan', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('nilai_sp2d', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('nomor_invoice', models.CharField(blank=True, max_length=100)),
                ('tanggal_invoice', models.DateField(blank=True, null=True)),
                ('jenis_spm', models.CharField(blank=True, max_length=100)),
                ('jenis_sp2d', models.CharField(blank=True, max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('cek_akun', models.CharField(blank=True, max_length=255)),
                ('nomor_spm_extracted', models.CharField(blank=True, max_length=100)),
                ('bulan_sp2d', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PERLU_DETAIL', 'Perlu Detail Akun'), ('COCOK', 'Cocok'), ('TIDAK_COCOK', 'Tidak Cocok'), ('DRAFT', 'Draft')], default='PERLU_DETAIL', max_length=20)),
                ('original_file', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sp2d_rows', to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_rows', to='sp2d.sp2dimportbatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sp2dimportbatch',
            index=models.Index(fields=['tahun', 'bulan'], name='sp2d_sp2dim_tahun_54d8b2_idx'),
        ),
        migrations.AddIndex(
            model_name='sp2dimportbatch',
            index=models.Index(fields=['status'], name='sp2d_sp2dim_status_e8d74e_idx'),
        ),
        migrations.AddIndex(
            model_name='sp2draw',
            index=models.Index(fields=['satker_code', 'nomor_spm_extracted'], name='sp2d_sp2dra_satker__69068f_idx'),
        ),
        migrations.AddIndex(
            model_name='sp2draw',
            index=models.Index(fields=['no_sp2d'], name='sp2d_sp2dra_no_sp2d_9d3678_idx'),
        ),
        migrations.AddIndex(
            model_name='sp2draw',
            index=models.Index(fields=['bulan_sp2d'], name='sp2d_sp2dra_bulan_s_f3a699_idx'),
        ),
        migrations.AddIndex(
            model_name='sp2draw',
            index=models.Index(fields=['status'], name='sp2d_sp2dra_status_e61c59_idx'),
        ),
    ]
