# Generated by Django 5.2.15 on 2026-07-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp2d', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp2dimportbatch',
            name='conflict_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sp2dimportbatch',
            name='created_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sp2dimportbatch',
            name='skipped_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sp2dimportbatch',
            name='updated_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sp2draw',
            name='identity_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sp2draw',
            name='tahun',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sp2dimportbatch',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('COMPLETED_WITH_REVIEW', 'Completed with Review'), ('FAILED', 'Failed')], default='DRAFT', max_length=30),
        ),
    ]
