# Generated by Django 5.2.15 on 2026-07-24 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp2d', '0002_sp2dimportbatch_conflict_rows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp2draw',
            name='last_import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_raw_rows', to='sp2d.sp2dimportbatch'),
        ),
    ]
