# Generated by Django 5.2.15 on 2026-07-24 04:13

import hashlib
from decimal import Decimal
from django.db import migrations


def get_legacy_year(row):
    if row.tahun:
        return row.tahun
    if row.import_batch_id:
        batch_tahun = row.import_batch.tahun
        if batch_tahun:
            return batch_tahun
    if row.tgl_sp2d:
        return row.tgl_sp2d.year
    if row.tanggal_selesai_sp2d:
        return row.tanggal_selesai_sp2d.year
    if row.tanggal_invoice:
        return row.tanggal_invoice.year
    return None

def normalize_money(value):
    if value is None:
        return ""
    try:
        dec = Decimal(str(value))
        if dec == dec.to_integral_value():
            return str(int(dec))
        return str(dec.normalize())
    except:
        return str(value)

def generate_legacy_identity(satker, sp2d_no, invoice_no, spm_no, tgl_sp2d, tgl_invoice, nilai, tahun):
    satker = str(satker or "").strip()
    sp2d_no = str(sp2d_no or "").strip()
    invoice_no = str(invoice_no or "").strip()
    spm_no = str(spm_no or "").strip()
    tgl_sp2d = str(tgl_sp2d or "").strip()
    tgl_invoice = str(tgl_invoice or "").strip()
    nilai = normalize_money(nilai)
    tahun = str(tahun or "").strip()

    if not satker or not tahun:
        return None

    if sp2d_no:
        base = f"{satker}|{sp2d_no}|{tahun}"
    else:
        doc_no = invoice_no or spm_no
        tgl = tgl_sp2d or tgl_invoice
        if not doc_no or not tgl or not nilai:
            return None
        base = f"{satker}|{doc_no}|{tgl}|{nilai}|{tahun}"
    
    return hashlib.sha256(base.encode("utf-8")).hexdigest()

def migrate_legacy_identity(apps, schema_editor):
    SP2DRaw = apps.get_model('sp2d', 'SP2DRaw')
    
    # Process all rows with NULL identity_key
    rows = SP2DRaw.objects.filter(identity_key__isnull=True).select_related('import_batch')
    
    # We need to ensure uniqueness.
    # Group by candidate_key to detect conflicts.
    key_to_rows = {}
    for row in rows:
        tahun = get_legacy_year(row)
        key = generate_legacy_identity(
            satker=row.satker_code,
            sp2d_no=row.no_sp2d,
            invoice_no=row.nomor_invoice,
            spm_no=row.nomor_spm_extracted,
            tgl_sp2d=row.tgl_sp2d,
            tgl_invoice=row.tanggal_invoice,
            nilai=row.nilai_sp2d,
            tahun=tahun
        )
        if key:
            if key not in key_to_rows:
                key_to_rows[key] = []
            key_to_rows[key].append((row, tahun))
    
    # Only update rows where key is unique
    for key, row_list in key_to_rows.items():
        if len(row_list) == 1:
            row, tahun = row_list[0]
            # Verify no existing row has this key
            if not SP2DRaw.objects.filter(identity_key=key).exists():
                row.identity_key = key
                row.tahun = tahun
                row.save(update_fields=['identity_key', 'tahun'])
        else:
            # Conflict. Leave identity_key NULL, but mark status
            for row, tahun in row_list:
                row.tahun = tahun
                row.status = "TIDAK_COCOK"
                if not row.cek_akun.startswith("[KONFLIK_LEGACY]"):
                    row.cek_akun = f"[KONFLIK_LEGACY] {row.cek_akun}"
                row.save(update_fields=['tahun', 'status', 'cek_akun'])

class Migration(migrations.Migration):

    dependencies = [
        ('sp2d', '0003_sp2draw_last_import_batch'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_identity, reverse_code=migrations.RunPython.noop),
    ]
