# Generated by Django 5.2.15 on 2026-07-24 07:18

from django.db import migrations, transaction
from decimal import Decimal
import hashlib

def normalize_sp2d_number(value):
    return str(value or "").strip().upper()

def normalize_money_for_identity(value):
    if value is None or value == "":
        return ""
    try:
        dec = Decimal(str(value))
        if dec == dec.to_integral_value():
            return str(int(dec))
        return str(dec.normalize())
    except:
        return str(value).strip()

def normalize_date_for_identity(value):
    if value is None or value == "":
        return ""
    return str(value).strip()

def build_identity_key(satker, sp2d_no, invoice_no, spm_no, tgl_sp2d, tgl_invoice, nilai, tahun):
    satker = normalize_sp2d_number(satker)
    tahun = str(tahun or "").strip()
    sp2d_no = normalize_sp2d_number(sp2d_no)
    invoice_no = normalize_sp2d_number(invoice_no)
    spm_no = normalize_sp2d_number(spm_no)
    tgl_sp2d = normalize_date_for_identity(tgl_sp2d)
    tgl_invoice = normalize_date_for_identity(tgl_invoice)
    nilai = normalize_money_for_identity(nilai)

    if not satker or not tahun:
        return None

    if sp2d_no:
        base = f"{satker}|{sp2d_no}|{tahun}"
    else:
        doc_no = invoice_no or spm_no
        tgl = tgl_sp2d or tgl_invoice
        if not doc_no or not tgl or not str(nilai):
            return None
        base = f"{satker}|{doc_no}|{tgl}|{nilai}|{tahun}"
    
    return hashlib.sha256(base.encode("utf-8")).hexdigest()

def finalize_legacy_identity_conflict_resolution(apps, schema_editor):
    SP2DRaw = apps.get_model('sp2d', 'SP2DRaw')
    
    rows = list(SP2DRaw.objects.all())
    
    # Calculate candidate keys
    key_to_rows = {}
    for row in rows:
        key = build_identity_key(
            satker=row.satker_code,
            sp2d_no=row.no_sp2d,
            invoice_no=row.nomor_invoice,
            spm_no=row.nomor_spm_extracted,
            tgl_sp2d=row.tgl_sp2d,
            tgl_invoice=row.tanggal_invoice,
            nilai=row.nilai_sp2d,
            tahun=row.tahun
        )
        if key:
            if key not in key_to_rows:
                key_to_rows[key] = []
            key_to_rows[key].append(row)
            
    # Process updates
    with transaction.atomic():
        for key, row_list in key_to_rows.items():
            if len(row_list) == 1:
                row = row_list[0]
                if row.identity_key != key:
                    # Clear any duplicates in db if exists just in case
                    SP2DRaw.objects.filter(identity_key=key).exclude(id=row.id).update(identity_key=None)
                    row.identity_key = key
                    row.save(update_fields=['identity_key'])
            else:
                # Conflict. Canonical winner is the newest by ID
                row_list.sort(key=lambda r: r.id, reverse=True)
                
                winner = row_list[0]
                losers = row_list[1:]
                
                # First, clear the losers to free up the unique constraint
                for row in losers:
                    row.identity_key = None
                    row.status = "TIDAK_COCOK"
                    if not row.cek_akun.startswith("[KONFLIK_LEGACY_NORMALISASI]"):
                        row.cek_akun = f"[KONFLIK_LEGACY_NORMALISASI] {row.cek_akun}"
                    row.save(update_fields=['identity_key', 'status', 'cek_akun'])
                
                # Then assign to winner
                SP2DRaw.objects.filter(identity_key=key).exclude(id=winner.id).update(identity_key=None)
                if winner.identity_key != key:
                    winner.identity_key = key
                    winner.save(update_fields=['identity_key'])

class Migration(migrations.Migration):

    dependencies = [
        ('sp2d', '0005_correct_legacy_identity_normalization'),
    ]

    operations = [
        migrations.RunPython(finalize_legacy_identity_conflict_resolution, reverse_code=migrations.RunPython.noop),
    ]
