"""
Google Drive OAuth Views - Central Archive Authorization.

HANYA admin/superuser boleh authorize.
Operator biasa ditolak.

URLs:
- /documents/drive/oauth/authorize/ - Start authorization
- /documents/drive/oauth/callback/ - Handle callback
- /documents/drive/oauth/status/ - Check status (JSON)
- /documents/drive/oauth/revoke/ - Revoke token
"""

import json
import logging

from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import Http404, JsonResponse
from django.shortcuts import redirect

from google_auth_oauthlib.flow import Flow

from apps.documents.services.google_drive import (
    check_central_oauth_status,
    oauth_enabled,
)
from apps.documents.services.google_oauth import (
    OAuthCredentialsNotConfigured,
    delete_all_central_credentials,
    has_central_token,
    is_oauth_configured,
    get_authorization_url_with_flow,
    get_central_token_path,
)


logger = logging.getLogger(__name__)

# Session keys for OAuth PKCE flow
_SESSION_KEY_OAUTH_STATE = "_oauth_state"
_SESSION_KEY_OAUTH_CODE_VERIFIER = "_oauth_code_verifier"
_SESSION_KEY_OAUTH_CLIENT_CONFIG = "_oauth_client_config"


def is_admin_user(user):
    """Check if user is superuser or staff."""
    return user.is_authenticated and (user.is_superuser or user.is_staff)


@login_required
@user_passes_test(is_admin_user)
def drive_oauth_authorize(request):
    """
    Redirect admin to Google OAuth authorization page.

    URL: /documents/drive/oauth/authorize/
    Permission: Admin/Superuser only

    Flow:
    1. Check if OAuth is configured
    2. Check if already authorized
    3. Generate authorization URL (PKCE code_verifier auto-generated by library)
    4. Store code_verifier in session for callback to use
    5. Redirect user to Google
    """
    if not oauth_enabled():
        messages.error(
            request,
            "Google Drive OAuth belum dikonfigurasi. "
            "Hubungi administrator untuk konfigurasi."
        )
        return redirect("core:dashboard")

    if not is_oauth_configured():
        messages.error(
            request,
            "OAuth credentials belum disetel. "
            "Set GOOGLE_DRIVE_OAUTH_CLIENT_ID dan GOOGLE_DRIVE_OAUTH_CLIENT_SECRET di environment."
        )
        return redirect("core:dashboard")

    if has_central_token():
        messages.info(
            request,
            "Google Drive sudah terotorisasi. "
            "Gunakan menu revoke untuk mengatur ulang jika perlu."
        )
        return redirect("core:dashboard")

    # Clear any stale session keys from a previous failed attempt
    for key in (_SESSION_KEY_OAUTH_STATE, _SESSION_KEY_OAUTH_CODE_VERIFIER, _SESSION_KEY_OAUTH_CLIENT_CONFIG):
        request.session.pop(key, None)

    try:
        state, auth_url, flow, client_config = get_authorization_url_with_flow()
        # Store PKCE code_verifier and client config in session so callback can restore them.
        # IMPORTANT: store client_config (with "web" top-level key), NOT flow.client_config
        # (flow.client_config is the unwrapped inner dict and would cause
        # "Client secrets must be for a web or installed app." in the callback).
        # We must persist it across the redirect so the callback can recreate the Flow with the SAME verifier.
        request.session[_SESSION_KEY_OAUTH_STATE] = state
        request.session[_SESSION_KEY_OAUTH_CODE_VERIFIER] = flow.code_verifier
        request.session[_SESSION_KEY_OAUTH_CLIENT_CONFIG] = client_config
        logger.info("[OAuth] authorize — state stored, code_verifier present=%s", bool(flow.code_verifier))
        return redirect(auth_url)
    except OAuthCredentialsNotConfigured as e:
        messages.error(request, f"OAuth configuration error: {e}")
        logger.error(f"OAuth auth_url failed: {e}")
        return redirect("core:dashboard")
    except Exception as e:
        messages.error(request, f"Failed to start OAuth flow: {e}")
        logger.error(f"OAuth auth_url exception: {e}")
        return redirect("core:dashboard")


@login_required
@user_passes_test(is_admin_user)
def drive_oauth_callback(request):
    """
    Handle OAuth callback from Google.

    URL: /documents/drive/oauth/callback/
    Permission: Admin/Superuser only

    Expected parameters:
    - code: Authorization code from Google
    - state: Encoded state with nonce
    - error: Error if authorization failed
    """
    # Check for error from Google
    error = request.GET.get("error")
    if error:
        error_description = request.GET.get("error_description", "")
        messages.error(
            request,
            f"Google authorization failed: {error} - {error_description}"
        )
        logger.warning(f"OAuth callback error: {error} - {error_description}")
        # Clean stale session keys
        for key in (_SESSION_KEY_OAUTH_STATE, _SESSION_KEY_OAUTH_CODE_VERIFIER, _SESSION_KEY_OAUTH_CLIENT_CONFIG):
            request.session.pop(key, None)
        return redirect("core:dashboard")

    # Get authorization code
    code = request.GET.get("code")
    state = request.GET.get("state")

    if not code:
        messages.error(request, "No authorization code received from Google.")
        return redirect("core:dashboard")

    if not state:
        messages.error(request, "No state parameter received. Possible CSRF attack.")
        return redirect("core:dashboard")

    # Retrieve PKCE code_verifier and client config from session
    saved_state = request.session.get(_SESSION_KEY_OAUTH_STATE)
    code_verifier = request.session.get(_SESSION_KEY_OAUTH_CODE_VERIFIER)
    client_config = request.session.get(_SESSION_KEY_OAUTH_CLIENT_CONFIG)

    logger.info(
        "[OAuth] callback — code_present=%s state_match=%s code_verifier_present=%s client_config_present=%s",
        bool(code), saved_state == state, bool(code_verifier), bool(client_config),
    )

    if not code_verifier or not client_config:
        messages.error(
            request,
            "OAuth session expired or invalid. Please restart the authorization process."
        )
        for key in (_SESSION_KEY_OAUTH_STATE, _SESSION_KEY_OAUTH_CODE_VERIFIER, _SESSION_KEY_OAUTH_CLIENT_CONFIG):
            request.session.pop(key, None)
        return redirect("core:dashboard")

    try:
        # Reconstruct Flow with the SAME code_verifier used during authorization.
        # Use from_client_config to create Flow with scopes, then set code_verifier manually.
        # This is critical for PKCE: code_verifier must match or token exchange fails.
        # Flow.__init__ signature: (oauth2session, client_type, client_config,
        #                           redirect_uri, code_verifier, autogenerate_code_verifier)
        # client_config has "web" top-level key and "redirect_uris" list
        flow = Flow.from_client_config(
            client_config=client_config,
            scopes=["https://www.googleapis.com/auth/drive.file"],
        )
        flow.redirect_uri = client_config["web"]["redirect_uris"][0]
        flow.code_verifier = code_verifier
        # Store state for CSRF validation
        flow.oauth2session.state = state

        # Exchange code for tokens
        flow.fetch_token(code=code)

        # Extract and persist the central token
        credentials = flow.credentials
        token_data = {
            "token": credentials.token,
            "refresh_token": credentials.refresh_token,
            "token_uri": credentials.token_uri,
            "client_id": credentials.client_id,
            "client_secret": credentials.client_secret,
            "scopes": credentials.scopes,
            "expiry": credentials.expiry.isoformat() if credentials.expiry else None,
        }

        from apps.documents.services.google_oauth import get_central_token_path
        token_path = get_central_token_path()
        with open(token_path, "w") as f:
            json.dump(token_data, f, indent=2)

        messages.success(
            request,
            "Berhasil authorize Google Drive. "
            "Arsip central INTERMILAN siap digunakan."
        )
        logger.info(f"OAuth authorization success by admin user {request.user.username}")

        # Clean temporary OAuth session keys after success
        for key in (_SESSION_KEY_OAUTH_STATE, _SESSION_KEY_OAUTH_CODE_VERIFIER, _SESSION_KEY_OAUTH_CLIENT_CONFIG):
            request.session.pop(key, None)

        return redirect("core:dashboard")

    except Exception as e:
        messages.error(request, f"Failed to complete authorization: {e}")
        logger.error(f"OAuth callback exception: {e}")
        # Clean stale session keys on failure
        for key in (_SESSION_KEY_OAUTH_STATE, _SESSION_KEY_OAUTH_CODE_VERIFIER, _SESSION_KEY_OAUTH_CLIENT_CONFIG):
            request.session.pop(key, None)
        return redirect("core:dashboard")


@login_required
def drive_oauth_status(request):
    """
    JSON endpoint to check OAuth status.

    URL: /documents/drive/oauth/status/
    Permission: Authenticated users (for UI status display)

    Returns:
        JSON with is_authorized, mode, error
    """
    if not request.headers.get("Content-Type", "").startswith("application/json"):
        raise Http404("JSON only")

    status = check_central_oauth_status()

    # Add admin info
    status["is_admin"] = request.user.is_superuser or request.user.is_staff

    return JsonResponse(status)


@login_required
@user_passes_test(is_admin_user)
def drive_oauth_revoke(request):
    """
    Revoke central OAuth token and folder ID, then redirect to re-authorize.

    URL: /documents/drive/oauth/revoke/
    Permission: Admin/Superuser only

    Use case:
    - Switch to different Google account
    - Token is invalid/corrupted
    - Reset archive connection
    """
    deleted = delete_all_central_credentials()

    if deleted:
        messages.info(
            request,
            "Token OAuth dan folder ID berhasil dihapus. "
            "Admin perlu authorize ulang untuk menggunakan Google Drive."
        )
        logger.info(f"OAuth credentials revoked by admin user {request.user.username}")
    else:
        messages.info(request, "Tidak ada token OAuth yang ditemukan.")

    return redirect("core:dashboard")
